<!DOCTYPE html><html lang="en"><head><meta charset="utf-8"><meta name="viewport" content="width=device-width,initial-scale=1"><title>Sign in · Greenfield International School</title><link rel="preconnect" href="https://fonts.googleapis.com"><link rel="preconnect" href="https://fonts.gstatic.com" crossorigin><link href="https://fonts.googleapis.com/css2?family=DM+Sans:wght@400;500;600;700&family=Manrope:wght@600;700;800&display=swap" rel="stylesheet">@vite(['resources/css/app.css','resources/js/app.js'])</head>
<body class="min-h-screen bg-[#edf4f0] pt-16">
<header class="fixed inset-x-0 top-0 z-50 border-b border-slate-200/80 bg-white/90 backdrop-blur-xl"><div class="mx-auto flex h-16 max-w-[1800px] items-center justify-between px-4 sm:px-8"><x-portfolio-back-button /><span class="text-right"><strong class="block text-[11px] font-extrabold text-ink">School LMS</strong><small class="block text-[8px] font-bold tracking-[.1em] text-brand-700 uppercase">Greenfield International</small></span></div></header>
<main class="grid min-h-[calc(100vh-4rem)] lg:grid-cols-[1.05fr_.95fr]">
    <section class="relative hidden overflow-hidden bg-[#0d3b34] p-14 text-white lg:flex lg:flex-col">
        <div class="absolute -right-32 -top-32 size-[520px] rounded-full bg-brand-500/20 blur-3xl"></div><div class="absolute -bottom-40 -left-20 size-[520px] rounded-full bg-cyan-300/10 blur-3xl"></div>
        <div class="relative my-auto max-w-2xl"><span class="inline-flex rounded-full border border-white/20 bg-white/10 px-4 py-2 text-xs font-bold tracking-wide text-emerald-100">ACADEMIC YEAR 2026–27</span><h1 class="mt-8 text-5xl font-extrabold leading-[1.08] tracking-tight text-white xl:text-6xl">Learning thrives when everyone is connected.</h1><p class="mt-6 max-w-xl text-lg leading-8 text-emerald-50/75">One thoughtful space for academics, progress, communication, and the moments that shape every learner.</p>
            <div class="mt-12 grid grid-cols-3 gap-4"><div class="rounded-2xl border border-white/10 bg-white/5 p-5"><p class="text-2xl font-extrabold">98.2%</p><p class="mt-1 text-xs text-emerald-100/70">Parent engagement</p></div><div class="rounded-2xl border border-white/10 bg-white/5 p-5"><p class="text-2xl font-extrabold">1,248</p><p class="mt-1 text-xs text-emerald-100/70">Active learners</p></div><div class="rounded-2xl border border-white/10 bg-white/5 p-5"><p class="text-2xl font-extrabold">96.4%</p><p class="mt-1 text-xs text-emerald-100/70">Attendance today</p></div></div>
        </div>
        <p class="relative text-xs text-emerald-100/50">© {{ date('Y') }} Greenfield International School · Learn with purpose</p>
    </section>
    <section class="flex items-center justify-center p-5 sm:p-10"><div class="w-full max-w-lg">
        <p class="text-sm font-bold text-brand-700">WELCOME BACK</p><h2 class="mt-2 text-3xl font-extrabold">Sign in to your school</h2><p class="mt-2 text-sm text-slate-500">Use your email address or username to continue.</p>
        <form method="POST" action="{{ route('login.store') }}" class="mt-8 grid gap-5">@csrf<div><label for="email">Email or username</label><input id="email" name="email" value="{{ old('email') }}" autocomplete="username" placeholder="name@greenfield.demo" required autofocus>@error('email')<p class="mt-1 text-xs text-rose-600">{{ $message }}</p>@enderror</div><div><div class="flex justify-between"><label for="password">Password</label><a href="{{ route('password.request') }}" class="text-xs font-bold text-brand-700">Forgot password?</a></div><input id="password" type="password" name="password" autocomplete="current-password" placeholder="Enter your password" required></div><label class="flex items-center gap-2 text-sm font-medium"><input type="checkbox" name="remember" value="1" class="size-4 w-auto rounded"> Keep me signed in</label><button class="btn-primary w-full py-3">Sign in securely</button></form>
        <div class="my-7 flex items-center gap-3"><div class="h-px flex-1 bg-slate-200"></div><span class="text-[11px] font-bold tracking-wider text-slate-400 uppercase">Explore the demo</span><div class="h-px flex-1 bg-slate-200"></div></div>
        <div class="grid grid-cols-2 gap-3">
            @foreach(['admin' => ['Principal','Dr. Maya Sharma'], 'teacher' => ['Teacher','Arjun Mehta'], 'student' => ['Student','Aarav Kapoor'], 'parent' => ['Parent','Neha Kapoor']] as $role => [$label,$name])
                <form method="POST" action="{{ route('demo.login', $role) }}">@csrf<button class="w-full rounded-xl border border-slate-200 bg-white p-3 text-left transition hover:-translate-y-0.5 hover:border-brand-500 hover:shadow-md" {{ config('lms.demo_mode') ? '' : 'disabled' }}><span class="text-xs font-bold text-ink">{{ $label }}</span><span class="mt-0.5 block text-[11px] text-slate-500">{{ $name }}</span></button></form>
            @endforeach
        </div>
        <div class="mt-5 rounded-xl bg-white/70 px-4 py-3 text-xs text-slate-500"><span class="font-bold text-slate-700">All demo accounts:</span> password <code class="rounded bg-slate-100 px-1.5 py-0.5 font-bold text-brand-700">Demo@123</code></div>
    </div></section>
</main></body></html>
