@extends('layouts.app')
@section('title', 'Dashboard')
@section('content')
<div class="flex flex-col gap-6">
    <div class="flex flex-col justify-between gap-4 sm:flex-row sm:items-end">
        <div><p class="text-xs font-bold tracking-wider text-brand-700 uppercase">{{ now()->format('l, j F') }}</p><h1 class="mt-1 text-2xl font-extrabold sm:text-3xl">Good {{ now()->hour < 12 ? 'morning' : (now()->hour < 17 ? 'afternoon' : 'evening') }}, {{ str(auth()->user()->name)->afterLast(' ') }}.</h1><p class="mt-1 text-sm text-slate-500">Here’s what’s happening across your learning community.</p></div>
        @if(auth()->user()->role === 'parent' && $children->count() > 1)<form method="GET" class="w-full sm:w-64"><label>Viewing child</label><select name="child" onchange="this.form.submit()">@foreach($children as $child)<option value="{{ $child->id }}" @selected($student?->id === $child->id)>{{ $child->name }} · {{ $child->studentProfile->academicClass->name }}{{ $child->studentProfile->academicClass->section }}</option>@endforeach</select></form>@endif
    </div>

    <section class="grid gap-4 sm:grid-cols-2 xl:grid-cols-4">
        @foreach($stats as $index => $stat)<article class="card p-5"><div class="flex items-start justify-between"><div><p class="text-xs font-semibold text-slate-500">{{ $stat['label'] }}</p><p class="mt-2 text-2xl font-extrabold tracking-tight text-ink">{{ $stat['value'] }}</p></div><div class="grid size-10 place-items-center rounded-xl stat-{{ $stat['tone'] }}"><i data-lucide="{{ ['users','book-open-check','calendar-check','indian-rupee'][$index] }}" class="size-5"></i></div></div><p class="mt-3 text-[11px] font-semibold text-slate-400">{{ $stat['change'] }}</p></article>@endforeach
    </section>

    <section class="grid gap-6 xl:grid-cols-[1.45fr_.75fr]">
        <div class="card overflow-hidden"><div class="flex items-center justify-between border-b border-slate-100 px-5 py-4"><div><h2 class="font-bold">Academic pulse</h2><p class="text-xs text-slate-500">Attendance and performance trend</p></div><span class="status-published">Healthy</span></div><div class="h-72 p-5"><canvas id="pulseChart"></canvas></div></div>
        <div class="card p-5"><div class="flex items-center justify-between"><h2 class="font-bold">Coming up</h2><a href="{{ route('modules.show','calendar') }}" class="text-xs font-bold text-brand-700">View calendar</a></div><div class="mt-5 grid gap-4">@forelse($events as $event)<div class="flex gap-3"><div class="grid size-12 shrink-0 place-items-center rounded-xl bg-slate-100 text-center"><span class="text-[10px] font-bold text-brand-700 uppercase">{{ $event->starts_at->format('M') }}</span><span class="-mt-2 text-lg font-extrabold text-ink">{{ $event->starts_at->format('d') }}</span></div><div><p class="text-sm font-bold text-ink">{{ $event->title }}</p><p class="mt-1 text-xs text-slate-500">{{ $event->starts_at->format('g:i A') }} · {{ $event->location }}</p></div></div>@empty<p class="text-sm text-slate-500">No upcoming events.</p>@endforelse</div></div>
    </section>

    <section class="grid gap-6 xl:grid-cols-3">
        <div class="card xl:col-span-2"><div class="flex items-center justify-between border-b border-slate-100 p-5"><div><h2 class="font-bold">Assignments & learning</h2><p class="text-xs text-slate-500">Current classroom activity</p></div><a href="{{ route('modules.show', auth()->user()->role === 'parent' ? 'homework' : 'assignments') }}" class="btn-secondary px-3 py-2 text-xs">See all</a></div><div class="divide-y divide-slate-100">@foreach($assignments as $assignment)<div class="flex items-center gap-4 p-5"><div class="grid size-10 shrink-0 place-items-center rounded-xl" style="background:{{ $assignment->subject->color }}18;color:{{ $assignment->subject->color }}"><i data-lucide="clipboard-check" class="size-5"></i></div><div class="min-w-0 flex-1"><p class="truncate text-sm font-bold text-ink">{{ $assignment->title }}</p><p class="mt-0.5 text-xs text-slate-500">{{ $assignment->subject->name }} · {{ $assignment->max_marks }} marks</p></div><div class="text-right"><p class="text-xs font-bold {{ $assignment->due_at->isPast() ? 'text-slate-400' : 'text-amber-700' }}">{{ $assignment->due_at->isPast() ? 'Closed' : 'Due '.$assignment->due_at->diffForHumans() }}</p><p class="mt-1 text-[11px] text-slate-400">{{ $assignment->due_at->format('d M, g:i A') }}</p></div></div>@endforeach</div></div>
        <div class="card p-5"><div class="flex items-center justify-between"><h2 class="font-bold">Latest notices</h2><a href="{{ route('modules.show','notices') }}" class="text-xs font-bold text-brand-700">All notices</a></div><div class="mt-4 grid gap-4">@foreach($notices as $notice)<article class="rounded-xl border border-slate-100 bg-slate-50/70 p-4"><div class="flex items-center gap-2"><span class="status-{{ $notice->priority }}">{{ $notice->priority }}</span><span class="text-[10px] text-slate-400">{{ $notice->published_at->diffForHumans() }}</span></div><h3 class="mt-2 text-sm font-bold">{{ $notice->title }}</h3><p class="mt-1 line-clamp-2 text-xs leading-5 text-slate-500">{{ $notice->body }}</p></article>@endforeach</div></div>
    </section>

    @if($student)<section class="card p-5"><div class="flex flex-col gap-5 md:flex-row md:items-center"><div class="grid size-16 place-items-center rounded-2xl text-xl font-extrabold text-white" style="background:{{ $student->avatar_color }}">{{ collect(explode(' ',$student->name))->map(fn($n)=>mb_substr($n,0,1))->take(2)->join('') }}</div><div class="flex-1"><p class="text-xs font-bold tracking-wider text-brand-700 uppercase">Learner snapshot</p><h2 class="mt-1 text-xl font-extrabold">{{ $student->name }}</h2><p class="text-sm text-slate-500">{{ $student->studentProfile->academicClass->name }}{{ $student->studentProfile->academicClass->section }} · {{ $student->studentProfile->admission_number }} · {{ $student->studentProfile->house }} House</p></div>@if($bookIssue)<div class="rounded-xl bg-blue-50 px-4 py-3"><p class="text-[10px] font-bold text-blue-600 uppercase">Library issue</p><p class="mt-1 text-sm font-bold text-blue-950">{{ $bookIssue->book_title }}</p><p class="text-xs text-blue-600">Due {{ $bookIssue->due_on->format('d M') }}</p></div>@endif</div></section>@endif
</div>
<script src="https://cdn.jsdelivr.net/npm/chart.js@4.4.7/dist/chart.umd.min.js"></script>
<script>document.addEventListener('DOMContentLoaded',()=>{const el=document.getElementById('pulseChart');if(!el||!window.Chart)return;new Chart(el,{type:'line',data:{labels:['Apr','May','Jun','Jul','Aug','Sep'],datasets:[{label:'Attendance',data:[93,95,94,96,95,97],borderColor:'#07866a',backgroundColor:'rgba(7,134,106,.08)',fill:true,tension:.4,pointRadius:3},{label:'Academic average',data:[78,81,80,84,86,88],borderColor:'#2563eb',tension:.4,pointRadius:3}]},options:{responsive:true,maintainAspectRatio:false,plugins:{legend:{position:'bottom',labels:{usePointStyle:true,boxWidth:8,padding:20}}},scales:{y:{min:60,max:100,grid:{color:'#edf1ef'},ticks:{callback:v=>v+'%'}},x:{grid:{display:false}}}}})})</script>
@endsection
