@extends('layouts.app')
@section('title', $title)
@section('content')
@php
    $role = auth()->user()->role;
    $resultModules = ['results', 'report-card', 'exam-marks', 'performance', 'progress'];
    $learningModules = ['content', 'lesson-plans', 'live-classes', 'recordings', 'study-materials', 'resources'];
    $recordModules = ['feedback', 'behavior', 'documents', 'certificates', 'notifications', 'settings', 'support'];
    $can = fn(string $permission): bool => $role === 'admin' || $grantedPermissions->contains($permission);
    $managedModules = match($role) {
        'admin' => ['users','roles','academics','subjects','curriculum','timetable','attendance','exams','notices','fees','library','calendar','documents','settings'],
        'teacher' => collect(['lesson-plans'=>'learning.manage','content'=>'learning.manage','attendance'=>'attendance.manage','homework'=>'assignments.manage','assignments'=>'assignments.manage','submissions'=>'assignments.manage','quizzes'=>'quizzes.manage','exam-marks'=>'marks.enter','feedback'=>'feedback.manage','behavior'=>'feedback.manage','notices'=>'notices.manage','resources'=>'learning.manage','messages'=>'messages.manage','doubts'=>'messages.manage'])->filter(fn($permission)=>$can($permission))->keys()->all(),
        'parent' => collect(['ptm'=>'ptm.manage','leave'=>'leave.manage','documents'=>'documents.manage','support'=>'support.manage','profile'=>'profile.update','messages'=>'messages.manage'])->filter(fn($permission)=>$can($permission))->keys()->all(),
        default => collect(['profile'=>'profile.update','messages'=>'messages.manage','doubts'=>'messages.manage'])->filter(fn($permission)=>$can($permission))->keys()->all(),
    };
    $createModules = match($role) {
        'admin' => ['users','academics','classes','subjects','curriculum','timetable','attendance','exams','notices','fees','library','calendar','documents','settings'],
        'teacher' => collect(['lesson-plans'=>'learning.manage','content'=>'learning.manage','attendance'=>'attendance.manage','homework'=>'assignments.manage','assignments'=>'assignments.manage','quizzes'=>'quizzes.manage','exam-marks'=>'marks.enter','feedback'=>'feedback.manage','behavior'=>'feedback.manage','notices'=>'notices.manage','resources'=>'learning.manage','messages'=>'messages.manage','doubts'=>'messages.manage'])->filter(fn($permission)=>$can($permission))->keys()->all(),
        'parent' => collect(['ptm'=>'ptm.manage','leave'=>'leave.manage','documents'=>'documents.manage','support'=>'support.manage','messages'=>'messages.manage'])->filter(fn($permission)=>$can($permission))->keys()->all(),
        default => collect(['messages'=>'messages.manage','doubts'=>'messages.manage'])->filter(fn($permission)=>$can($permission))->keys()->all(),
    };
    $createIcon = match($module) {
        'users' => 'user-plus', 'academics', 'classes' => 'school', 'subjects' => 'book-open-check',
        'attendance' => 'user-check', 'assignments', 'homework' => 'clipboard-plus', 'quizzes' => 'circle-help',
        'exam-marks', 'exams' => 'file-check-2', 'fees' => 'wallet-cards', 'library' => 'book-plus',
        'calendar' => 'calendar-plus', 'documents' => 'file-plus-2', 'messages', 'doubts' => 'message-circle-plus',
        'support' => 'life-buoy', 'ptm' => 'handshake', 'leave' => 'calendar-off', 'notices' => 'megaphone',
        default => 'plus',
    };
@endphp
<div x-data="{ modal: null, query: '' }" class="flex flex-col gap-6">
    <header class="flex flex-col justify-between gap-4 sm:flex-row sm:items-end">
        <div>
            <div class="flex items-center gap-2 text-xs font-bold text-slate-400"><a href="{{ route('dashboard') }}" class="hover:text-brand-700">Dashboard</a><span>/</span><span>{{ $title }}</span></div>
            <h1 class="mt-2 text-2xl font-extrabold sm:text-3xl">{{ $title }}</h1>
            <p class="mt-1 max-w-3xl text-sm text-slate-500">{{ $description }}</p>
        </div>
        <div class="flex flex-wrap gap-2">
            <button onclick="window.print()" class="btn-secondary"><i data-lucide="printer" class="size-4"></i><span class="hidden sm:inline">Print</span></button>
            @if(in_array($module, $createModules))<button @click="modal='create'" class="btn-primary"><i data-lucide="plus" class="size-4"></i>Create</button>
            @elseif(in_array($module, $managedModules))<a href="#manage-records" class="btn-secondary"><i data-lucide="pencil" class="size-4"></i>{{ $module === 'submissions' ? 'Review' : ($module === 'roles' ? 'Configure' : 'Edit') }}</a>@endif
        </div>
    </header>

    @if($role === 'parent' && $children->count() > 1 && in_array($module, ['child-profile', 'progress', 'attendance', 'homework', 'exams', 'results', 'feedback', 'behavior', 'fees', 'leave', 'documents', 'ptm']))
        <form method="GET" class="card flex flex-col gap-3 p-4 sm:flex-row sm:items-center">
            <div class="grid size-10 shrink-0 place-items-center rounded-xl bg-brand-50 text-brand-700"><i data-lucide="users" class="size-5"></i></div>
            <div class="flex-1"><label class="mb-0">Viewing records for</label><select name="child" onchange="this.form.submit()" class="mt-1 max-w-sm">@foreach($children as $child)<option value="{{ $child->id }}" @selected($student?->id === $child->id)>{{ $child->name }} · {{ $child->studentProfile->academicClass->name }}{{ $child->studentProfile->academicClass->section }}</option>@endforeach</select></div>
        </form>
    @endif

    @if($module === 'reports')
        @php $attendanceTotal=$attendance->count(); $attendanceRate=$attendanceTotal ? round($attendance->whereIn('status',['present','late'])->count()/$attendanceTotal*100,1) : 0; $balance=$fees->sum(fn($fee)=>(float)$fee->amount-(float)$fee->paid_amount); @endphp
        <div class="grid gap-4 sm:grid-cols-2 xl:grid-cols-4">
            @foreach([['Learners',$users->where('role','student')->count(),'users'],['Attendance',$attendanceRate.'%','user-check'],['Published results',$results->where('is_published',true)->count(),'chart-no-axes-combined'],['Outstanding fees','₹'.number_format($balance),'receipt']] as [$label,$value,$icon])
                <article class="card p-5"><div class="flex items-center justify-between"><p class="text-xs font-bold text-slate-500">{{ $label }}</p><i data-lucide="{{ $icon }}" class="size-5 text-brand-600"></i></div><p class="mt-3 text-3xl font-extrabold">{{ $value }}</p><p class="mt-2 text-xs text-slate-400">Live demo data · AY {{ config('lms.academic_year') }}</p></article>
            @endforeach
        </div>
        <div class="grid gap-5 lg:grid-cols-2"><section class="card p-6"><h2 class="font-extrabold">Academic snapshot</h2><div class="mt-5 grid gap-4">@foreach($subjects->sortByDesc('progress')->take(6) as $subject)<div><div class="mb-2 flex justify-between text-xs"><span class="font-semibold">{{ $subject->name }}</span><strong>{{ $subject->progress }}%</strong></div><div class="h-2 rounded-full bg-slate-100"><div class="h-full rounded-full" style="width:{{ $subject->progress }}%;background:{{ $subject->color }}"></div></div></div>@endforeach</div></section><section class="card p-6"><h2 class="font-extrabold">Leadership attention</h2><div class="mt-5 grid gap-3">@foreach([['Outstanding fee balance','₹'.number_format($balance),'amber'],['Pending leave requests',$leaves->where('status','pending')->count(),'blue'],['Unread priority notices',$notices->whereIn('priority',['important','urgent'])->count(),'rose']] as [$label,$value,$tone])<div class="flex items-center justify-between rounded-xl bg-slate-50 p-4"><span class="text-sm font-semibold">{{ $label }}</span><span class="badge bg-{{ $tone }}-50 text-{{ $tone }}-700">{{ $value }}</span></div>@endforeach</div></section></div>
    @elseif($module === 'roles')
        <div class="grid gap-5 md:grid-cols-2">@foreach(['admin'=>'Principal / Admin','teacher'=>'Teacher','student'=>'Student','parent'=>'Parent'] as $roleKey=>$roleName)@php $enabled=$roleKey==='admin' ? collect(config('lms.permissions')) : $rolePermissions->get($roleKey,collect())->where('is_allowed',true)->mapWithKeys(fn($permission)=>[$permission->permission=>config('lms.permissions.'.$permission->permission)]); @endphp<article class="card p-6"><div class="flex items-center justify-between"><div class="grid size-11 place-items-center rounded-xl bg-brand-50 text-brand-700"><i data-lucide="shield-check" class="size-5"></i></div><span class="status-approved">{{ $enabled->count() }} permissions</span></div><h2 class="mt-4 text-lg font-extrabold">{{ $roleName }}</h2><ul class="mt-4 grid gap-2">@foreach($enabled->take(6) as $label)<li class="flex gap-2 text-sm text-slate-600"><i data-lucide="check" class="mt-0.5 size-4 text-emerald-600"></i>{{ $label }}</li>@endforeach</ul></article>@endforeach</div>
    @elseif($module === 'users')
        <div class="grid gap-4 sm:grid-cols-2 lg:grid-cols-4">@foreach(['student'=>'Students','teacher'=>'Teachers','parent'=>'Parents','admin'=>'Administrators'] as $key=>$label)<div class="card p-5"><p class="text-xs font-semibold text-slate-500">{{ $label }}</p><p class="mt-2 text-3xl font-extrabold">{{ $users->where('role',$key)->count() }}</p><p class="mt-2 text-xs text-emerald-700">Active in AY {{ config('lms.academic_year') }}</p></div>@endforeach</div>
        <div class="card overflow-hidden"><div class="flex flex-col gap-3 border-b border-slate-100 p-4 sm:flex-row"><div class="relative flex-1"><i data-lucide="search" class="absolute left-3 top-1/2 size-4 -translate-y-1/2 text-slate-400"></i><input x-model="query" class="pl-9" placeholder="Search users…"></div><button class="btn-secondary"><i data-lucide="download" class="size-4"></i>Export</button></div><div class="overflow-x-auto"><table><thead><tr><th>User</th><th>Role</th><th>Username</th><th>Contact</th><th>Status</th></tr></thead><tbody>@foreach($users as $person)<tr x-show="'{{ strtolower($person->name.' '.$person->email.' '.$person->role) }}'.includes(query.toLowerCase())"><td><div class="flex items-center gap-3"><div class="grid size-9 place-items-center rounded-xl text-xs font-bold text-white" style="background:{{ $person->avatar_color }}">{{ mb_substr($person->name,0,1) }}</div><div><p class="font-bold">{{ $person->name }}</p><p class="text-xs text-slate-500">{{ $person->email }}</p></div></div></td><td><span class="badge bg-slate-100 text-slate-700">{{ $person->role }}</span></td><td>{{ $person->username }}</td><td>{{ $person->phone ?? '—' }}</td><td><span class="status-approved">{{ $person->status }}</span></td></tr>@endforeach</tbody></table></div></div>
    @elseif(in_array($module, ['academics','classes']))
        <div class="grid gap-5 md:grid-cols-2 xl:grid-cols-3">@forelse($classes as $class)<article class="card p-5"><div class="flex justify-between"><div class="grid size-11 place-items-center rounded-xl bg-blue-50 text-blue-700"><i data-lucide="school" class="size-5"></i></div><span class="badge bg-slate-100 text-slate-600">{{ $class->academic_year }}</span></div><h2 class="mt-5 text-xl font-extrabold">{{ $class->name }} · Section {{ $class->section }}</h2><p class="mt-1 text-sm text-slate-500">Room {{ $class->room }} · {{ $class->students_count }}/{{ $class->capacity }} learners</p><div class="mt-5 h-2 overflow-hidden rounded-full bg-slate-100"><div class="h-full rounded-full bg-brand-500" style="width:{{ min(100,$class->students_count/$class->capacity*100) }}%"></div></div></article>@empty<div class="card col-span-full p-12 text-center text-slate-500">No classes are assigned yet.</div>@endforelse</div>
    @elseif($module === 'subjects')
        <div class="grid gap-5 md:grid-cols-2 xl:grid-cols-3">@foreach($subjects as $subject)<article class="card p-5"><div class="h-1.5 rounded-full" style="background:{{ $subject->color }}"></div><div class="mt-5 flex justify-between"><div class="grid size-11 place-items-center rounded-xl" style="background:{{ $subject->color }}15;color:{{ $subject->color }}"><i data-lucide="book-open" class="size-5"></i></div><span class="text-xs font-bold text-slate-400">{{ $subject->code }}</span></div><h2 class="mt-4 text-lg font-extrabold">{{ $subject->name }}</h2><p class="text-sm text-slate-500">{{ $subject->teacher?->name }} · {{ $subject->academicClass->name }}{{ $subject->academicClass->section }}</p><div class="mt-5"><div class="mb-2 flex justify-between text-xs"><span>Syllabus progress</span><strong>{{ $subject->progress }}%</strong></div><div class="h-2 rounded-full bg-slate-100"><div class="h-full rounded-full" style="width:{{ $subject->progress }}%;background:{{ $subject->color }}"></div></div></div></article>@endforeach</div>
    @elseif($module === 'attendance')
        @php $present=$attendance->where('status','present')->count(); $total=$attendance->count(); @endphp
        <div class="grid gap-4 sm:grid-cols-3"><div class="card p-5"><p class="text-xs text-slate-500">Records shown</p><p class="mt-2 text-3xl font-extrabold">{{ $total }}</p></div><div class="card p-5"><p class="text-xs text-slate-500">Present</p><p class="mt-2 text-3xl font-extrabold text-emerald-700">{{ $present }}</p></div><div class="card p-5"><p class="text-xs text-slate-500">Attendance rate</p><p class="mt-2 text-3xl font-extrabold text-blue-700">{{ $total ? round($attendance->whereIn('status',['present','late'])->count()/$total*100,1) : 0 }}%</p></div></div>
        <div class="card overflow-hidden"><div class="border-b border-slate-100 p-4"><input x-model="query" placeholder="Filter by student or status…"></div><div class="overflow-x-auto"><table><thead><tr><th>Date</th><th>Student</th><th>Status</th><th>Remarks</th><th>Marked by</th></tr></thead><tbody>@forelse($attendance as $record)<tr x-show="'{{ strtolower($record->student->name.' '.$record->status) }}'.includes(query.toLowerCase())"><td class="font-semibold">{{ $record->date->format('d M Y') }}</td><td>{{ $record->student->name }}</td><td><span class="status-{{ $record->status }}">{{ $record->status }}</span></td><td>{{ $record->remarks ?? '—' }}</td><td>{{ $record->marker->name }}</td></tr>@empty<tr><td colspan="5" class="py-12 text-center text-slate-500">No attendance has been recorded yet.</td></tr>@endforelse</tbody></table></div></div>
    @elseif($module === 'submissions')
        <div class="grid gap-4 sm:grid-cols-3"><div class="card p-5"><p class="text-xs text-slate-500">Submissions</p><p class="mt-2 text-3xl font-extrabold">{{ $submissions->count() }}</p></div><div class="card p-5"><p class="text-xs text-slate-500">Awaiting review</p><p class="mt-2 text-3xl font-extrabold text-amber-700">{{ $submissions->where('status','submitted')->count() }}</p></div><div class="card p-5"><p class="text-xs text-slate-500">Graded</p><p class="mt-2 text-3xl font-extrabold text-emerald-700">{{ $submissions->where('status','graded')->count() }}</p></div></div>
        <div class="card overflow-hidden"><div class="p-5"><h2 class="font-bold">Recent submissions</h2></div><div class="overflow-x-auto"><table><thead><tr><th>Student</th><th>Assignment</th><th>Submitted</th><th>Status</th><th>Score</th></tr></thead><tbody>@forelse($submissions as $submission)<tr><td>{{ $submission->student->name }}</td><td>{{ $submission->assignment->title }}</td><td>{{ $submission->submitted_at->format('d M, g:i A') }}</td><td><span class="status-{{ $submission->status }}">{{ $submission->status }}</span></td><td>{{ $submission->marks !== null ? $submission->marks.'/'.$submission->assignment->max_marks : 'Awaiting review' }}</td></tr>@empty<tr><td colspan="5" class="py-12 text-center text-slate-500">No submissions yet.</td></tr>@endforelse</tbody></table></div></div>
    @elseif(in_array($module, ['assignments','homework']))
        <div class="grid gap-5 lg:grid-cols-2">@foreach($assignments as $assignment)@php $ownSubmission=$assignment->submissions->first(); @endphp<article class="card p-5"><div class="flex items-start justify-between gap-3"><div class="grid size-11 place-items-center rounded-xl" style="background:{{ $assignment->subject->color }}15;color:{{ $assignment->subject->color }}"><i data-lucide="clipboard-list" class="size-5"></i></div><span class="{{ $ownSubmission ? 'status-approved' : ($assignment->due_at->isPast() ? 'status-graded' : 'status-pending') }}">{{ $ownSubmission ? str($ownSubmission->status)->headline() : ($assignment->due_at->isPast() ? 'Closed' : 'Due '.$assignment->due_at->diffForHumans()) }}</span></div><h2 class="mt-4 text-lg font-extrabold">{{ $assignment->title }}</h2><p class="mt-1 text-xs font-bold" style="color:{{ $assignment->subject->color }}">{{ $assignment->subject->name }} · {{ $assignment->max_marks }} marks</p><p class="mt-3 text-sm leading-6 text-slate-500">{{ $assignment->instructions }}</p><div class="mt-4 flex items-center justify-between border-t border-slate-100 pt-4"><span class="text-xs text-slate-500">@if(in_array($role,['student','parent'])){{ $ownSubmission ? 'Submitted '.$ownSubmission->submitted_at->diffForHumans() : 'Not submitted' }}@else{{ $assignment->submissions->count() }} submission(s)@endif</span>@if($role==='student' && !$assignment->due_at->isPast() && (!$ownSubmission || $ownSubmission->status!=='graded'))<button @click="modal='submit-{{ $assignment->id }}'" class="btn-primary px-3 py-2 text-xs">{{ $ownSubmission ? 'Update work' : 'Submit work' }}</button>@endif</div></article>@endforeach</div>
    @elseif($module === 'quizzes')
        <div class="grid gap-5 lg:grid-cols-2">@foreach($quizzes as $quiz)<article class="card p-5"><div class="flex justify-between"><div class="grid size-11 place-items-center rounded-xl bg-violet-50 text-violet-700"><i data-lucide="circle-help" class="size-5"></i></div><span class="status-published">{{ count($quiz->questions) }} questions</span></div><h2 class="mt-4 text-lg font-extrabold">{{ $quiz->title }}</h2><p class="mt-1 text-sm text-slate-500">{{ $quiz->subject->name }} · {{ $quiz->duration_minutes }} minutes</p><div class="mt-5 border-t border-slate-100 pt-4">@if($role==='student')@if($attempts->has($quiz->id))<p class="font-bold text-emerald-700">Completed · {{ $attempts[$quiz->id]->score }}/{{ $attempts[$quiz->id]->total }}</p>@else<button @click="modal='quiz-{{ $quiz->id }}'" class="btn-primary">Start quiz</button>@endif @else<p class="text-xs text-slate-500">Available until {{ $quiz->available_until?->format('d M, g:i A') }}</p>@endif</div></article>@endforeach</div>
    @elseif($module === 'question-bank')
        <div class="card overflow-hidden"><div class="border-b border-slate-100 p-4"><input x-model="query" placeholder="Search questions, quizzes or subjects…"></div><div class="overflow-x-auto"><table><thead><tr><th>Question</th><th>Subject</th><th>Source</th><th>Options</th><th>Answer</th></tr></thead><tbody>@foreach($questionBank as $question)<tr x-show="'{{ strtolower($question['question'].' '.$question['subject'].' '.$question['quiz']) }}'.includes(query.toLowerCase())"><td class="max-w-md font-semibold">{{ $question['question'] }}</td><td>{{ $question['subject'] }}</td><td>{{ $question['quiz'] }}</td><td>{{ count($question['options']) }}</td><td><span class="status-approved">{{ $question['answer'] }}</span></td></tr>@endforeach</tbody></table></div></div>
    @elseif($module === 'exams')
        <div class="grid gap-5 lg:grid-cols-2">@foreach($records as $record)<article class="card p-5"><div class="flex items-start justify-between gap-3"><div class="grid size-11 place-items-center rounded-xl bg-rose-50 text-rose-700"><i data-lucide="file-clock" class="size-5"></i></div><span class="status-pending">{{ $record->status }}</span></div><h2 class="mt-4 text-lg font-extrabold">{{ $record->title }}</h2><p class="mt-1 text-sm font-semibold text-slate-600">{{ $record->subtitle }}</p><p class="mt-3 text-sm text-slate-500">{{ $record->description }}</p></article>@endforeach</div>
    @elseif(in_array($module, $resultModules))
        <div class="grid gap-4 sm:grid-cols-3"><div class="card p-5"><p class="text-xs text-slate-500">Published subjects</p><p class="mt-2 text-3xl font-extrabold">{{ $results->count() }}</p></div><div class="card p-5"><p class="text-xs text-slate-500">Average score</p><p class="mt-2 text-3xl font-extrabold text-blue-700">{{ $results->count() ? round($results->avg(fn($r)=>$r->marks/$r->max_marks*100)) : 0 }}%</p></div><div class="card p-5"><p class="text-xs text-slate-500">Highest grade</p><p class="mt-2 text-3xl font-extrabold text-emerald-700">{{ $results->sortByDesc(fn($r)=>$r->marks/$r->max_marks)->first()?->grade ?? '—' }}</p></div></div>
        <div class="card overflow-hidden"><div class="flex items-center justify-between p-5"><div><h2 class="font-bold">Term I Examination</h2><p class="text-xs text-slate-500">Published result ledger</p></div><button onclick="window.print()" class="btn-secondary text-xs">Download report</button></div><div class="overflow-x-auto"><table><thead><tr>@if(in_array($role,['admin','teacher']))<th>Student</th>@endif<th>Subject</th><th>Marks</th><th>Percentage</th><th>Grade</th><th>Publication</th></tr></thead><tbody>@forelse($results as $result)<tr>@if(in_array($role,['admin','teacher']))<td>{{ $result->student->name }}</td>@endif<td class="font-bold">{{ $result->subject->name }}</td><td>{{ $result->marks }}/{{ $result->max_marks }}</td><td>{{ round($result->marks/$result->max_marks*100) }}%</td><td><span class="badge bg-blue-50 text-blue-700">{{ $result->grade }}</span></td><td><span class="status-{{ $result->is_published ? 'published' : 'pending' }}">{{ $result->is_published ? 'Published' : 'Draft' }}</span></td></tr>@empty<tr><td colspan="6" class="py-12 text-center text-slate-500">No published results are available.</td></tr>@endforelse</tbody></table></div></div>
    @elseif($module === 'fees')
        <div class="rounded-2xl border border-amber-200 bg-amber-50 p-4 text-sm text-amber-900"><strong>Record-management only:</strong> payments shown here were received offline; this demo never initiates a financial transaction.</div>
        <div class="card overflow-hidden"><div class="overflow-x-auto"><table><thead><tr><th>Student</th><th>Fee item</th><th>Amount</th><th>Paid</th><th>Balance</th><th>Due</th><th>Status</th><th></th></tr></thead><tbody>@forelse($fees as $fee)<tr><td>{{ $fee->student->name }}</td><td><p class="font-bold">{{ $fee->fee_type }}</p><p class="text-xs text-slate-500">{{ $fee->reference }}</p></td><td>₹{{ number_format((float)$fee->amount) }}</td><td>₹{{ number_format((float)$fee->paid_amount) }}</td><td class="font-bold">₹{{ number_format((float)$fee->amount-(float)$fee->paid_amount) }}</td><td>{{ $fee->due_date->format('d M Y') }}</td><td><span class="status-{{ $fee->status }}">{{ $fee->status }}</span></td><td>@if($role==='admin' && $fee->status!=='paid')<button @click="modal='fee-{{ $fee->id }}'" class="btn-secondary px-3 py-2 text-xs">Record payment</button>@endif</td></tr>@empty<tr><td colspan="8" class="py-12 text-center text-slate-500">No fee records for this learner.</td></tr>@endforelse</tbody></table></div></div>
    @elseif($module === 'library')
        <div class="grid gap-5 md:grid-cols-2 xl:grid-cols-3">@forelse($bookIssues as $issue)<article class="card overflow-hidden"><div class="h-24 bg-gradient-to-br from-blue-950 to-blue-600 p-5 text-white"><i data-lucide="book-open" class="size-7"></i></div><div class="p-5"><span class="status-{{ $issue->status }}">{{ $issue->status }}</span><h2 class="mt-3 text-lg font-extrabold">{{ $issue->book_title }}</h2><p class="text-sm text-slate-500">{{ $issue->author }}</p><p class="mt-4 text-xs">Issued to <strong>{{ $issue->student->name }}</strong><br>{{ $issue->status === 'returned' ? 'Returned '.$issue->returned_on?->format('d M Y') : 'Due '.$issue->due_on->format('d M Y') }}</p></div></article>@empty<div class="card col-span-full py-16 text-center text-slate-500">No library issues found.</div>@endforelse</div>
    @elseif($module === 'notices')
        <div class="grid gap-5 lg:grid-cols-2">@foreach($notices as $notice)<article class="card p-5"><div class="flex items-center justify-between"><span class="status-{{ $notice->priority }}">{{ $notice->priority }}</span><span class="text-xs text-slate-400">{{ $notice->published_at->diffForHumans() }}</span></div><h2 class="mt-4 text-lg font-extrabold">{{ $notice->title }}</h2><p class="mt-2 text-sm leading-6 text-slate-600">{{ $notice->body }}</p><p class="mt-4 border-t border-slate-100 pt-3 text-xs text-slate-400">{{ $notice->author->name }} · Audience: {{ $notice->audience }}</p></article>@endforeach</div>
    @elseif($module === 'timetable')
        @php $days=['Mon','Tue','Wed','Thu','Fri']; @endphp
        <div class="card overflow-hidden"><div class="overflow-x-auto"><div class="grid min-w-[820px] grid-cols-5 gap-px bg-slate-200">@foreach($days as $day)<div class="bg-slate-50 p-3 text-center text-xs font-bold text-slate-500">{{ $day }}</div>@endforeach @foreach($days as $day)<div class="min-h-72 bg-white p-3"><div class="grid gap-3">@foreach($records->filter(fn($record)=>($record->meta['day']??'')===$day) as $record)<article class="rounded-xl border border-slate-200 p-3"><div class="flex justify-between text-[10px] font-bold text-brand-700"><span>PERIOD {{ $record->meta['period'] }}</span><span>{{ $record->meta['room'] }}</span></div><h2 class="mt-2 text-sm font-extrabold">{{ $record->title }}</h2><p class="mt-1 text-xs text-slate-500">{{ $record->description }}</p></article>@endforeach</div></div>@endforeach</div></div></div>
    @elseif($module === 'ptm')
        <div class="grid gap-5 lg:grid-cols-2">@foreach($records as $record)<article class="card p-5"><div class="flex items-start justify-between"><div class="grid size-11 place-items-center rounded-xl bg-violet-50 text-violet-700"><i data-lucide="handshake" class="size-5"></i></div><span class="status-{{ $record->status }}">{{ $record->status }}</span></div><h2 class="mt-4 text-lg font-extrabold">{{ $record->title }}</h2><p class="mt-1 text-sm font-semibold text-slate-600">{{ $record->subtitle }}</p><p class="mt-3 text-sm text-slate-500">{{ $record->description }}</p><p class="mt-4 border-t border-slate-100 pt-3 text-xs text-slate-400">{{ $record->student?->name }} · {{ $record->owner?->name }}</p></article>@endforeach</div>
    @elseif($module === 'calendar')
        <div class="grid gap-5 lg:grid-cols-[1.2fr_.8fr]"><div class="card p-5"><div class="grid grid-cols-7 gap-2 text-center">@foreach(['Mon','Tue','Wed','Thu','Fri','Sat','Sun'] as $day)<div class="pb-2 text-[10px] font-bold text-slate-400 uppercase">{{ $day }}</div>@endforeach @foreach(range(1,35) as $day)<div class="grid aspect-square place-items-center rounded-xl text-sm {{ in_array($day,[5,7,9,12,15,18]) ? 'bg-brand-600 font-bold text-white' : ($day<3 ? 'text-slate-300' : 'hover:bg-slate-100') }}">{{ $day }}</div>@endforeach</div></div><div class="card p-5"><h2 class="font-bold">Scheduled events</h2><div class="mt-5 grid gap-4">@foreach($events as $event)<div class="border-l-2 border-brand-500 pl-4"><p class="text-xs font-bold text-brand-700">{{ $event->starts_at->format('D, d M · g:i A') }}</p><h3 class="mt-1 text-sm font-bold">{{ $event->title }}</h3><p class="text-xs text-slate-500">{{ $event->location }}</p></div>@endforeach</div></div></div>
    @elseif($module === 'leave')
        <div class="card overflow-hidden"><div class="overflow-x-auto"><table><thead><tr><th>Requested by</th><th>Student</th><th>Dates</th><th>Reason</th><th>Status</th><th>Action</th></tr></thead><tbody>@forelse($leaves as $leave)<tr><td>{{ $leave->user->name }}</td><td>{{ $leave->student?->name ?? 'Self' }}</td><td>{{ $leave->from_date->format('d M') }} – {{ $leave->to_date->format('d M Y') }}</td><td class="max-w-sm">{{ $leave->reason }}</td><td><span class="status-{{ $leave->status }}">{{ $leave->status }}</span></td><td>@if($role==='admin'&&$leave->status==='pending')<div class="flex gap-1">@foreach(['approved'=>'Approve','rejected'=>'Reject'] as $status=>$label)<form method="POST" action="{{ route('leave.review',$leave) }}">@csrf @method('PATCH')<input type="hidden" name="status" value="{{ $status }}"><button class="btn-secondary px-2 py-1.5 text-xs">{{ $label }}</button></form>@endforeach</div>@else—@endif</td></tr>@empty<tr><td colspan="6" class="py-12 text-center text-slate-500">No leave requests found.</td></tr>@endforelse</tbody></table></div></div>
    @elseif(in_array($module, ['messages','doubts']))
        <div class="card overflow-hidden"><div class="divide-y divide-slate-100">@forelse($messages as $message)<article class="flex gap-4 p-5"><div class="grid size-10 shrink-0 place-items-center rounded-xl bg-blue-50 text-blue-700"><i data-lucide="message-circle" class="size-5"></i></div><div><div class="flex flex-wrap items-center gap-2"><h2 class="font-bold">{{ $message->subject }}</h2><span class="text-xs text-slate-400">{{ $message->created_at->diffForHumans() }}</span></div><p class="mt-1 text-xs font-semibold text-slate-500">{{ $message->sender->name }} → {{ $message->recipient->name }}</p><p class="mt-3 text-sm leading-6">{{ $message->body }}</p></div></article>@empty<div class="py-16 text-center text-slate-500">Your inbox is clear.</div>@endforelse</div></div>
    @elseif(in_array($module, ['curriculum','chapters']))
        <div class="grid gap-5 md:grid-cols-2">@foreach($records as $record)<article class="card p-5"><div class="flex items-center justify-between"><div><span class="text-[10px] font-bold tracking-wider text-brand-700 uppercase">{{ $record->subtitle }}</span><h2 class="mt-1 text-lg font-extrabold">{{ $record->title }}</h2></div><strong class="text-xl text-brand-700">{{ $record->meta['progress'] ?? 0 }}%</strong></div><p class="mt-3 text-sm text-slate-500">{{ $record->description }}</p><div class="mt-5 h-2 rounded-full bg-slate-100"><div class="h-full rounded-full bg-brand-500" style="width:{{ $record->meta['progress'] ?? 0 }}%"></div></div>@if(isset($record->meta['standard']))<p class="mt-3 text-xs text-slate-400">Standard: {{ $record->meta['standard'] }}</p>@endif</article>@endforeach</div>
    @elseif(in_array($module, $learningModules))
        @php $filteredItems=$learningItems->filter(fn($item)=>match($module){'live-classes'=>$item->type==='live-class','recordings'=>$item->type==='recording','lesson-plans'=>$item->type==='lesson-plan','content','study-materials'=>$item->type==='content',default=>true}); @endphp
        <div class="grid gap-5 lg:grid-cols-2">@forelse($filteredItems as $item)<article class="card flex gap-4 p-5"><div class="grid size-12 shrink-0 place-items-center rounded-xl bg-brand-50 text-brand-700"><i data-lucide="{{ $item->type==='live-class'?'video':($item->type==='recording'?'circle-play':'file-text') }}" class="size-5"></i></div><div><span class="text-[10px] font-bold tracking-wider text-brand-700 uppercase">{{ str($item->type)->replace('-',' ') }} · {{ $item->subject->name }}</span><h2 class="mt-1 font-extrabold">{{ $item->title }}</h2><p class="mt-2 text-sm leading-6 text-slate-500">{{ $item->description }}</p>@if($item->scheduled_at)<p class="mt-2 text-xs font-semibold text-slate-400">{{ $item->scheduled_at->format('d M Y · g:i A') }}</p>@endif @if($item->url)<a href="{{ $item->url }}" target="_blank" rel="noopener" class="mt-3 inline-flex items-center gap-1 text-xs font-bold text-brand-700">Open resource <i data-lucide="external-link" class="size-3"></i></a>@endif</div></article>@empty<div class="card col-span-full p-12 text-center text-slate-500">No resources in this category yet.</div>@endforelse</div>
    @elseif(in_array($module, $recordModules))
        @if($module === 'notifications')<div class="flex items-center justify-between rounded-xl bg-blue-50 px-4 py-3 text-sm text-blue-800"><span><strong>{{ $records->where('status','unread')->count() }} unread</strong> updates for your family</span><i data-lucide="bell-ring" class="size-5"></i></div>@endif
        <div class="grid gap-5 lg:grid-cols-2">@forelse($records as $record)<article class="card p-5"><div class="flex items-start justify-between gap-3"><div class="grid size-11 shrink-0 place-items-center rounded-xl bg-brand-50 text-brand-700"><i data-lucide="{{ match($module){'feedback'=>'message-square-heart','behavior'=>'sparkles','documents'=>'files','certificates'=>'badge-check','notifications'=>$record->meta['icon']??'bell','settings'=>'settings-2','support'=>'life-buoy',default=>'file-text'} }}" class="size-5"></i></div><span class="status-{{ $record->status }}">{{ str($record->status)->headline() }}</span></div><h2 class="mt-4 text-lg font-extrabold">{{ $record->title }}</h2><p class="mt-1 text-sm font-semibold text-slate-600">{{ $record->subtitle }}</p><p class="mt-3 text-sm leading-6 text-slate-500">{{ $record->description }}</p><div class="mt-4 flex flex-wrap items-center justify-between gap-2 border-t border-slate-100 pt-3 text-xs text-slate-400"><span>@if($record->student){{ $record->student->name }} · @endif{{ $record->owner?->name }}</span><span>{{ $record->occurred_at?->format('d M Y') }}</span></div>@if(data_get($record->meta,'attachment_path'))<a class="mt-3 inline-flex items-center gap-1 text-xs font-bold text-brand-700" href="{{ route('module-records.download',$record) }}"><i data-lucide="download" class="size-3"></i> Download {{ data_get($record->meta,'original_name','attachment') }}</a>@endif @if($module==='notifications'&&$record->status==='unread')<form method="POST" action="{{ route('notifications.read',$record) }}" class="mt-3">@csrf @method('PATCH')<button class="text-xs font-bold text-brand-700">Mark as read</button></form>@endif</article>@empty<div class="card col-span-full p-12 text-center text-slate-500">No records are available in this view.</div>@endforelse</div>
    @elseif(in_array($module, ['profile','child-profile']))
        @php $person=$module === 'child-profile' ? ($student ?? auth()->user()) : auth()->user(); @endphp
        <div class="grid gap-6 lg:grid-cols-[.7fr_1.3fr]"><div class="card p-6 text-center"><div class="mx-auto grid size-24 place-items-center rounded-3xl text-3xl font-extrabold text-white" style="background:{{ $person->avatar_color }}">{{ mb_substr($person->name,0,1) }}</div><h2 class="mt-4 text-xl font-extrabold">{{ $person->name }}</h2><p class="text-sm capitalize text-slate-500">{{ $person->role }}</p><span class="status-approved mt-4">Active</span></div><div class="card p-6"><h2 class="font-bold">Profile details</h2><dl class="mt-5 grid gap-5 sm:grid-cols-2">@foreach(['Email'=>$person->email,'Phone'=>$person->phone ?? 'Not provided','Username'=>$person->username,'Admission no.'=>$person->studentProfile?->admission_number ?? '—','Class'=>trim(($person->studentProfile?->academicClass?->name ?? '').' '.($person->studentProfile?->academicClass?->section ?? '')) ?: '—','House'=>$person->studentProfile?->house ?? '—','Blood group'=>$person->studentProfile?->blood_group ?? '—','Academic year'=>config('lms.academic_year')] as $label=>$value)<div><dt class="text-xs font-bold text-slate-400 uppercase">{{ $label }}</dt><dd class="mt-1 font-semibold">{{ $value }}</dd></div>@endforeach</dl></div></div>
    @elseif($module === 'audit')
        <div class="card overflow-hidden"><div class="overflow-x-auto"><table><thead><tr><th>Time</th><th>User</th><th>Action</th><th>Entity</th><th>IP address</th></tr></thead><tbody>@forelse($auditLogs as $log)<tr><td>{{ $log->created_at->format('d M, H:i') }}</td><td>{{ $log->user?->name ?? 'System' }}</td><td class="font-bold">{{ $log->action }}</td><td>{{ class_basename($log->subject_type ?? 'System') }} #{{ $log->subject_id }}</td><td class="font-mono text-xs">{{ $log->ip_address }}</td></tr>@empty<tr><td colspan="5" class="py-12 text-center text-slate-500">Activity will appear here as the demo is used.</td></tr>@endforelse</tbody></table></div></div>
    @else
        <div class="card p-12 text-center"><i data-lucide="construction" class="mx-auto size-10 text-slate-300"></i><h2 class="mt-4 font-extrabold">No view configured</h2><p class="mt-2 text-sm text-slate-500">This navigation item needs a dedicated workflow.</p></div>
    @endif

    @include('modules.management')
    @include('modules.dialogs')
</div>
@endsection
