<div x-show="modal" x-cloak :aria-hidden="modal ? 'false' : 'true'" class="fixed inset-0 z-[70] grid place-items-center bg-slate-950/50 p-3 backdrop-blur-sm sm:p-4" @keydown.escape.window="modal=null">
    <div role="dialog" aria-modal="true" aria-label="Action form" @click.outside="modal=null" class="card max-h-[92vh] w-full max-w-2xl overflow-y-auto p-5 sm:p-6">
        <div class="sticky -top-5 z-10 -mx-5 -mt-5 mb-5 flex items-center justify-between gap-4 border-b border-slate-200 bg-white/95 px-5 py-4 backdrop-blur-sm sm:-top-6 sm:-mx-6 sm:-mt-6 sm:px-6">
            <div class="flex min-w-0 items-center gap-3"><span class="grid size-10 shrink-0 place-items-center rounded-xl bg-brand-50 text-brand-700"><i data-lucide="{{ $createIcon }}" class="size-5"></i></span><div class="min-w-0"><p class="text-[10px] font-bold tracking-wider text-brand-700 uppercase" x-show="modal==='create'">New record · {{ str($role)->headline() }}</p><h2 class="truncate text-lg font-extrabold" x-text="modal==='create' ? 'Create {{ addslashes($title) }}' : 'Complete this action'">Complete this action</h2></div></div>
            <button type="button" @click="modal=null" class="rounded-lg p-2 hover:bg-slate-100" aria-label="Close dialog"><i data-lucide="x" class="size-5"></i></button>
        </div>

        <div x-show="modal==='create'" class="grid gap-5">
            @if($module === 'users' && $role === 'admin')
                <form method="POST" action="{{ route('users.store') }}" class="create-form">@csrf @include('modules.forms.user', ['person' => null])<button class="btn-primary">Create user</button></form>
            @elseif(in_array($module, ['academics','classes']) && $role === 'admin')
                <form method="POST" action="{{ route('academic-classes.store') }}" class="create-form">@csrf @include('modules.forms.academic-class', ['item' => null])<button class="btn-primary">Create class</button></form>
            @elseif($module === 'subjects' && $role === 'admin')
                <form method="POST" action="{{ route('subjects.store') }}" class="create-form">@csrf @include('modules.forms.subject', ['item' => null])<button class="btn-primary">Create subject</button></form>
            @elseif($module === 'attendance' && in_array($role, ['admin','teacher']))
                <form method="POST" action="{{ route('attendance.store') }}" class="create-form">@csrf<div><label>Student</label><select name="student_id" required>@foreach($attendanceStudents as $person)<option value="{{ $person->id }}">{{ $person->name }}</option>@endforeach</select></div><div><label>Date</label><input type="date" name="date" max="{{ now()->toDateString() }}" value="{{ now()->toDateString() }}" required></div><div><label>Status</label><select name="status"><option>present</option><option>absent</option><option>late</option><option>excused</option></select></div><div><label>Remarks</label><input name="remarks" placeholder="Optional context"></div><button class="btn-primary">Create attendance record</button></form>
            @elseif(in_array($module, ['assignments','homework']) && in_array($role, ['admin','teacher']))
                <form method="POST" action="{{ route('assignments.store') }}" class="create-form">@csrf<div><label>Subject</label><select name="subject_id" required>@foreach($subjects as $subject)<option value="{{ $subject->id }}">{{ $subject->name }} · {{ $subject->academicClass->name }}{{ $subject->academicClass->section }}</option>@endforeach</select></div><div><label>Title</label><input name="title" required></div><div class="sm:col-span-2"><label>Instructions</label><textarea name="instructions" rows="4" required></textarea></div><div><label>Due at</label><input type="datetime-local" name="due_at" min="{{ now()->addHour()->format('Y-m-d\TH:i') }}" required></div><div><label>Maximum marks</label><input type="number" name="max_marks" value="20" min="1" required></div><div><label>Save as</label><select name="status"><option value="published">Published</option><option value="draft">Draft</option></select></div><button class="btn-primary">Create assignment</button></form>
            @elseif($module === 'notices' && in_array($role, ['admin','teacher']))
                <form method="POST" action="{{ route('notices.store') }}" class="create-form">@csrf<div><label>Title</label><input name="title" required></div><div><label>Priority</label><select name="priority"><option>normal</option><option>important</option><option>urgent</option></select></div><div class="sm:col-span-2"><label>Audience</label><select name="audience"><option>all</option><option>teacher</option><option>student</option><option>parent</option></select></div><div class="sm:col-span-2"><label>Notice</label><textarea name="body" rows="5" required></textarea></div><button class="btn-primary">Create notice</button></form>
            @elseif($module === 'leave' && $can('leave.manage'))
                <form method="POST" action="{{ route('leave.store') }}" class="create-form">@csrf @if($role === 'parent')<div class="sm:col-span-2"><label>Child</label><select name="student_id">@foreach($children as $child)<option value="{{ $child->id }}" @selected($student?->id === $child->id)>{{ $child->name }}</option>@endforeach</select></div>@endif<div><label>From</label><input type="date" name="from_date" min="{{ now()->toDateString() }}" required></div><div><label>To</label><input type="date" name="to_date" min="{{ now()->toDateString() }}" required></div><div class="sm:col-span-2"><label>Reason</label><textarea name="reason" rows="4" required></textarea></div><button class="btn-primary">Create leave request</button></form>
            @elseif(in_array($module, ['messages','doubts']) && $can('messages.manage'))
                <form method="POST" action="{{ route('messages.store') }}" class="create-form">@csrf<div><label>Recipient</label><select name="recipient_id" required>@foreach($contactOptions as $person)<option value="{{ $person->id }}">{{ $person->name }} · {{ $person->role }}</option>@endforeach</select></div><div><label>Subject</label><input name="subject" required></div><div class="sm:col-span-2"><label>Message</label><textarea name="body" rows="5" required></textarea></div><button class="btn-primary">Create message</button></form>
            @elseif($module === 'support' && $can('support.manage'))
                <form method="POST" action="{{ route('support.store') }}" class="create-form">@csrf<div><label>Related learner</label><select name="student_id"><option value="">Family account / general</option>@foreach($children as $child)<option value="{{ $child->id }}">{{ $child->name }}</option>@endforeach</select></div><div><label>Category</label><select name="category"><option>Profile & records</option><option>Academics</option><option>Transport</option><option>Fees</option><option>Technical</option></select></div><div><label>Subject</label><input name="subject" required></div><div><label>Priority</label><select name="priority"><option>Normal</option><option>High</option><option>Urgent</option></select></div><div class="sm:col-span-2"><label>Details</label><textarea name="details" rows="5" minlength="10" required></textarea></div><button class="btn-primary">Create support ticket</button></form>
            @elseif($module === 'ptm' && $can('ptm.manage'))
                <form method="POST" action="{{ route('ptm.store') }}" class="create-form">@csrf<div><label>Child</label><select name="student_id" required>@foreach($children as $child)<option value="{{ $child->id }}" @selected($student?->id === $child->id)>{{ $child->name }}</option>@endforeach</select></div><div><label>Teacher</label><select name="teacher_id" required>@foreach($contactOptions as $person)<option value="{{ $person->id }}">{{ $person->name }}</option>@endforeach</select></div><div class="sm:col-span-2"><label>Preferred date and time</label><input type="datetime-local" name="preferred_at" min="{{ now()->addDay()->format('Y-m-d\TH:i') }}" required></div><div class="sm:col-span-2"><label>Discussion topic</label><textarea name="topic" rows="4" minlength="10" required></textarea></div><button class="btn-primary">Create meeting request</button></form>
            @elseif($module === 'quizzes' && in_array($role, ['admin','teacher']))
                <form method="POST" action="{{ route('quizzes.store') }}" class="create-form">@csrf @include('modules.forms.quiz-create')<button class="btn-primary">Create quiz</button></form>
            @elseif(in_array($module, ['lesson-plans','content','resources']) && in_array($role, ['admin','teacher']))
                <form method="POST" action="{{ route('learning-items.store') }}" class="create-form">@csrf @include('modules.forms.learning-item', ['item' => null])<button class="btn-primary">Create resource</button></form>
            @elseif($module === 'exam-marks' && in_array($role, ['admin','teacher']))
                <form method="POST" action="{{ route('exam-results.store') }}" class="create-form">@csrf @include('modules.forms.exam-result', ['item' => null])<button class="btn-primary">Create exam result</button></form>
            @elseif($module === 'fees' && $role === 'admin')
                <form method="POST" action="{{ route('fee-records.store') }}" class="create-form">@csrf @include('modules.forms.fee', ['item' => null])<button class="btn-primary">Create fee record</button></form>
            @elseif($module === 'library' && $role === 'admin')
                <form method="POST" action="{{ route('book-issues.store') }}" class="create-form">@csrf @include('modules.forms.book-issue', ['item' => null])<button class="btn-primary">Create book issue</button></form>
            @elseif($module === 'calendar' && $role === 'admin')
                <form method="POST" action="{{ route('school-events.store') }}" class="create-form">@csrf @include('modules.forms.event', ['item' => null])<button class="btn-primary">Create event</button></form>
            @elseif($module === 'exams' && $role === 'admin')
                <section><h3 class="mb-3 font-extrabold">Exam schedule</h3><form method="POST" action="{{ route('module-records.store') }}" class="create-form">@csrf @include('modules.forms.module-record', ['item' => null])<button class="btn-primary">Create exam schedule</button></form></section>
                <section class="border-t border-slate-200 pt-5"><h3 class="mb-3 font-extrabold">Learner result</h3><form method="POST" action="{{ route('exam-results.store') }}" class="create-form">@csrf @include('modules.forms.exam-result', ['item' => null])<button class="btn-primary">Create exam result</button></form></section>
            @elseif($module === 'documents')
                <section><h3 class="mb-3 font-extrabold">Document</h3><form method="POST" action="{{ route('module-records.store') }}" class="create-form" enctype="multipart/form-data">@csrf @include('modules.forms.module-record', ['item' => null])<button class="btn-primary">Create document</button></form></section>
                @if($role === 'admin')<section class="border-t border-slate-200 pt-5"><h3 class="mb-3 font-extrabold">Learner certificate</h3><form method="POST" action="{{ route('module-records.store') }}" class="create-form" enctype="multipart/form-data">@csrf @include('modules.forms.module-record', ['item' => null, 'recordModule' => 'certificates'])<button class="btn-primary">Create certificate</button></form></section>@endif
            @elseif(in_array($module, ['curriculum','timetable','settings','feedback','behavior']))
                <form method="POST" action="{{ route('module-records.store') }}" class="create-form">@csrf @include('modules.forms.module-record', ['item' => null])<button class="btn-primary">Create record</button></form>
            @endif
        </div>

        @foreach($assignments as $assignment)@php $existingSubmission=$assignment->submissions->first(); @endphp @if($role === 'student' && (!$existingSubmission || $existingSubmission->status!=='graded'))<form x-show="modal==='submit-{{ $assignment->id }}'" method="POST" action="{{ route('submissions.store',$assignment) }}" class="grid gap-4">@csrf<h3 class="font-bold">{{ $assignment->title }}</h3><div><label>Your answer</label><textarea name="answer" rows="8" minlength="20" required placeholder="Write a complete response…">{{ $existingSubmission?->answer }}</textarea></div><button class="btn-primary">{{ $existingSubmission ? 'Resubmit assignment' : 'Submit assignment' }}</button></form>@endif @endforeach
        @foreach($quizzes as $quiz)@if($role === 'student' && ! $attempts->has($quiz->id))<form x-show="modal==='quiz-{{ $quiz->id }}'" method="POST" action="{{ route('quizzes.attempt',$quiz) }}" class="grid gap-5">@csrf<h3 class="font-bold">{{ $quiz->title }}</h3>@foreach($quiz->questions as $index=>$question)<fieldset><legend class="mb-2 text-sm font-bold">{{ $index+1 }}. {{ $question['question'] }}</legend><div class="grid gap-2">@foreach($question['options'] as $option)<label class="flex cursor-pointer items-center gap-2 rounded-xl border border-slate-200 p-3"><input type="radio" name="answers[{{ $index }}]" value="{{ $option }}" class="size-4 w-auto" required>{{ $option }}</label>@endforeach</div></fieldset>@endforeach<button class="btn-primary">Finish quiz</button></form>@endif @endforeach
        @foreach($fees as $fee)@if($role === 'admin' && $fee->status !== 'paid')<form x-show="modal==='fee-{{ $fee->id }}'" method="POST" action="{{ route('fees.payments.store',$fee) }}" class="grid gap-4">@csrf<h3 class="font-bold">{{ $fee->student->name }} · {{ $fee->fee_type }}</h3><p class="rounded-xl bg-amber-50 p-3 text-sm">Outstanding: <strong>₹{{ number_format((float)$fee->amount-(float)$fee->paid_amount) }}</strong></p><div><label>Amount received</label><input type="number" step="0.01" min="0.01" max="{{ (float)$fee->amount-(float)$fee->paid_amount }}" name="amount" required></div><div><label>Method</label><select name="payment_method"><option>Cash</option><option>Cheque</option><option>Bank transfer</option></select></div><div><label>Reference</label><input name="reference" required></div><div><label>Received on</label><input type="date" name="paid_on" max="{{ now()->toDateString() }}" value="{{ now()->toDateString() }}" required></div><button class="btn-primary">Record offline payment</button></form>@endif @endforeach
    </div>
</div>
