@if(in_array($module, $managedModules))
<section id="manage-records" class="card scroll-mt-24 p-5 sm:p-6">
    <div class="flex flex-col gap-2 border-b border-slate-100 pb-5 sm:flex-row sm:items-center sm:justify-between">
        <div><p class="text-xs font-bold tracking-wider text-brand-700 uppercase">Authorised workspace</p><h2 class="mt-1 text-xl font-extrabold">Edit & review {{ strtolower($title) }}</h2><p class="mt-1 text-sm text-slate-500">Update or remove existing records within your role permissions.</p></div>
        <span class="status-approved">{{ $role === 'admin' ? 'Full access' : 'Scoped access' }}</span>
    </div>

    @if($module === 'users' && $role === 'admin')
        <div class="manage-list">@foreach($users as $person)<details class="manage-details"><summary><span>{{ $person->name }}</span><span class="badge bg-slate-100 text-slate-600">{{ $person->role }}</span></summary><form method="POST" action="{{ route('users.update',$person) }}" class="manage-form">@csrf @method('PATCH') @include('modules.forms.user', ['person' => $person])<button class="btn-primary">Save changes</button></form>@if(!auth()->user()->is($person))<form method="POST" action="{{ route('users.destroy',$person) }}" onsubmit="return confirm('Delete this user? Linked users should be deactivated instead.')" class="px-4 pb-4">@csrf @method('DELETE')<button class="text-sm font-bold text-rose-600">Delete user</button></form>@endif</details>@endforeach</div>
    @elseif($module === 'roles' && $role === 'admin')
        <div class="manage-list">@foreach(['teacher','student','parent'] as $managedRole)<form method="POST" action="{{ route('roles.permissions.update',$managedRole) }}" class="rounded-xl border border-slate-200 p-4">@csrf @method('PUT')<div class="flex items-center justify-between"><h3 class="font-extrabold">{{ str($managedRole)->headline() }}</h3><span class="text-xs text-slate-400">{{ $rolePermissions->get($managedRole,collect())->where('is_allowed',true)->count() }} enabled</span></div><div class="mt-4 grid gap-3 sm:grid-cols-2 lg:grid-cols-3">@foreach(config('lms.permissions') as $permission=>$label)@php $enabled=$rolePermissions->get($managedRole,collect())->firstWhere('permission',$permission)?->is_allowed; @endphp<label class="flex cursor-pointer items-center gap-3 rounded-xl border border-slate-200 bg-white p-3 text-sm"><input type="checkbox" name="permissions[]" value="{{ $permission }}" class="size-4 w-auto" @checked($enabled)><span>{{ $label }}</span></label>@endforeach</div><button class="btn-primary mt-4">Save {{ $managedRole }} permissions</button></form>@endforeach</div>
    @elseif(in_array($module, ['academics','classes']) && $role === 'admin')
        <div class="manage-list">@foreach($classes as $item)<details class="manage-details"><summary>{{ $item->name }} · Section {{ $item->section }}</summary><form method="POST" action="{{ route('academic-classes.update',$item) }}" class="manage-form">@csrf @method('PATCH') @include('modules.forms.academic-class', ['item' => $item])<button class="btn-primary">Save changes</button></form><form method="POST" action="{{ route('academic-classes.destroy',$item) }}" onsubmit="return confirm('Delete this class?')" class="px-4 pb-4">@csrf @method('DELETE')<button class="text-sm font-bold text-rose-600">Delete class</button></form></details>@endforeach</div>
    @elseif($module === 'subjects' && $role === 'admin')
        <div class="manage-list">@foreach($subjects as $item)<details class="manage-details"><summary>{{ $item->name }} · {{ $item->code }}</summary><form method="POST" action="{{ route('subjects.update',$item) }}" class="manage-form">@csrf @method('PATCH') @include('modules.forms.subject', ['item' => $item])<button class="btn-primary">Save changes</button></form><form method="POST" action="{{ route('subjects.destroy',$item) }}" onsubmit="return confirm('Delete this subject?')" class="px-4 pb-4">@csrf @method('DELETE')<button class="text-sm font-bold text-rose-600">Delete subject</button></form></details>@endforeach</div>
    @elseif(in_array($module, ['curriculum','timetable','exams','documents','settings','feedback','behavior']))
        <div class="manage-list">@foreach($records as $item)@if($role === 'admin' || $item->owner_id === auth()->id())<details class="manage-details"><summary><span>{{ $item->title }}</span><span class="status-{{ $item->status }}">{{ str($item->status)->headline() }}</span></summary><form method="POST" action="{{ route('module-records.update',$item) }}" class="manage-form" @if(in_array($item->module,['documents','certificates'])) enctype="multipart/form-data" @endif>@csrf @method('PATCH') @include('modules.forms.module-record', ['item' => $item])<button class="btn-primary">Save changes</button></form><form method="POST" action="{{ route('module-records.destroy',$item) }}" onsubmit="return confirm('Delete this record?')" class="px-4 pb-4">@csrf @method('DELETE')<button class="text-sm font-bold text-rose-600">Delete record</button></form></details>@endif @endforeach</div>
        @if($module==='exams' && $role==='admin')<div class="manage-list">@foreach($results as $item)<details class="manage-details"><summary>{{ $item->student->name }} · {{ $item->subject->name }} · {{ $item->marks }}/{{ $item->max_marks }}</summary><form method="POST" action="{{ route('exam-results.update',$item) }}" class="manage-form">@csrf @method('PATCH') @include('modules.forms.exam-result', ['item' => $item])<button class="btn-primary">Update marks</button></form><form method="POST" action="{{ route('exam-results.destroy',$item) }}" onsubmit="return confirm('Delete these marks?')" class="px-4 pb-4">@csrf @method('DELETE')<button class="text-sm font-bold text-rose-600">Delete marks</button></form></details>@endforeach</div>@endif
    @elseif($module === 'attendance')
        <p class="mt-5 text-sm text-slate-500">Use <strong>Create</strong> above to mark attendance. Recent authorised records can be corrected below.</p><div class="manage-list">@foreach($attendance->take(12) as $item)<details class="manage-details"><summary>{{ $item->student->name }} · {{ $item->date->format('d M Y') }} · {{ str($item->status)->headline() }}</summary><form method="POST" action="{{ route('attendance.update',$item) }}" class="manage-form">@csrf @method('PATCH')<div><label>Status</label><select name="status">@foreach(['present','absent','late','excused'] as $status)<option @selected($item->status===$status)>{{ $status }}</option>@endforeach</select></div><div class="sm:col-span-2"><label>Remarks</label><input name="remarks" value="{{ $item->remarks }}"></div><button class="btn-primary">Update attendance</button></form><form method="POST" action="{{ route('attendance.destroy',$item) }}" onsubmit="return confirm('Delete this attendance record?')" class="px-4 pb-4">@csrf @method('DELETE')<button class="text-sm font-bold text-rose-600">Delete record</button></form></details>@endforeach</div>
    @elseif(in_array($module, ['assignments','homework']))
        <p class="mt-5 text-sm text-slate-500">Use <strong>Create</strong> above to publish an assignment. Teachers may remove drafts; administrators may remove any assignment.</p><div class="manage-list">@foreach($assignments as $item)<details class="manage-details"><summary><span>{{ $item->title }}</span><span class="status-{{ $item->status }}">{{ $item->status }}</span></summary><form method="POST" action="{{ route('assignments.update',$item) }}" class="manage-form">@csrf @method('PATCH') @include('modules.forms.assignment', ['item' => $item])<button class="btn-primary">Save assignment</button></form>@if($role==='admin'||$item->status==='draft')<form method="POST" action="{{ route('assignments.destroy',$item) }}" onsubmit="return confirm('Delete this assignment?')" class="px-4 pb-4">@csrf @method('DELETE')<button class="text-sm font-bold text-rose-600">Delete assignment</button></form>@endif</details>@endforeach</div>
    @elseif($module === 'submissions')
        <div class="manage-list">@foreach($submissions as $item)<details class="manage-details"><summary><span>{{ $item->student->name }} · {{ $item->assignment->title }}</span><span class="status-{{ $item->status }}">{{ $item->status }}</span></summary><form method="POST" action="{{ route('submissions.grade',$item) }}" class="manage-form">@csrf @method('PATCH')<div><label>Marks (max {{ $item->assignment->max_marks }})</label><input type="number" step="0.5" min="0" max="{{ $item->assignment->max_marks }}" name="marks" value="{{ $item->marks }}" required></div><div class="sm:col-span-2"><label>Feedback</label><textarea name="feedback" rows="3" required>{{ $item->feedback }}</textarea></div><button class="btn-primary">Release grade</button></form></details>@endforeach</div>
    @elseif($module === 'quizzes')
        <div class="manage-list">@foreach($quizzes as $item)<details class="manage-details"><summary><span>{{ $item->title }}</span><span class="status-{{ $item->status }}">{{ $item->status }}</span></summary><form method="POST" action="{{ route('quizzes.update',$item) }}" class="manage-form">@csrf @method('PATCH')<div><label>Title</label><input name="title" value="{{ $item->title }}" required></div><div><label>Duration (minutes)</label><input type="number" name="duration_minutes" min="1" value="{{ $item->duration_minutes }}" required></div><div><label>Available until</label><input type="datetime-local" name="available_until" value="{{ $item->available_until?->format('Y-m-d\TH:i') }}" required></div><div><label>Status</label><select name="status">@foreach(['draft','published','closed'] as $status)<option @selected($item->status===$status)>{{ $status }}</option>@endforeach</select></div><button class="btn-primary">Save quiz</button></form>@if($role==='admin'||$item->status==='draft')<form method="POST" action="{{ route('quizzes.destroy',$item) }}" onsubmit="return confirm('Delete this quiz?')" class="px-4 pb-4">@csrf @method('DELETE')<button class="text-sm font-bold text-rose-600">Delete quiz</button></form>@endif</details>@endforeach</div>
    @elseif(in_array($module, ['lesson-plans','content','resources']))
        <div class="manage-list">@foreach($learningItems as $item)<details class="manage-details"><summary><span>{{ $item->title }}</span><span class="status-{{ $item->status }}">{{ $item->status }}</span></summary><form method="POST" action="{{ route('learning-items.update',$item) }}" class="manage-form">@csrf @method('PATCH') @include('modules.forms.learning-item', ['item' => $item])<button class="btn-primary">Save resource</button></form>@if($role==='admin'||$item->status==='draft')<form method="POST" action="{{ route('learning-items.destroy',$item) }}" onsubmit="return confirm('Delete this resource?')" class="px-4 pb-4">@csrf @method('DELETE')<button class="text-sm font-bold text-rose-600">Delete resource</button></form>@endif</details>@endforeach</div>
    @elseif($module === 'exam-marks')
        <div class="manage-list">@foreach($results as $item)<details class="manage-details"><summary>{{ $item->student->name }} · {{ $item->subject->name }} · {{ $item->marks }}/{{ $item->max_marks }}</summary><form method="POST" action="{{ route('exam-results.update',$item) }}" class="manage-form">@csrf @method('PATCH') @include('modules.forms.exam-result', ['item' => $item])<button class="btn-primary">Update marks</button></form><form method="POST" action="{{ route('exam-results.destroy',$item) }}" onsubmit="return confirm('Delete these marks?')" class="px-4 pb-4">@csrf @method('DELETE')<button class="text-sm font-bold text-rose-600">Delete marks</button></form></details>@endforeach</div>
    @elseif($module === 'fees' && $role === 'admin')
        <div class="manage-list">@foreach($fees as $item)<details class="manage-details"><summary>{{ $item->student->name }} · {{ $item->fee_type }}</summary><form method="POST" action="{{ route('fee-records.update',$item) }}" class="manage-form">@csrf @method('PATCH') @include('modules.forms.fee', ['item' => $item])<button class="btn-primary">Save fee record</button></form><form method="POST" action="{{ route('fee-records.destroy',$item) }}" onsubmit="return confirm('Delete this fee record?')" class="px-4 pb-4">@csrf @method('DELETE')<button class="text-sm font-bold text-rose-600">Delete record</button></form></details>@endforeach</div>
    @elseif($module === 'library' && $role === 'admin')
        <div class="manage-list">@foreach($bookIssues as $item)<details class="manage-details"><summary>{{ $item->book_title }} · {{ $item->student->name }}</summary><form method="POST" action="{{ route('book-issues.update',$item) }}" class="manage-form">@csrf @method('PATCH') @include('modules.forms.book-issue', ['item' => $item])<button class="btn-primary">Save issue</button></form><form method="POST" action="{{ route('book-issues.destroy',$item) }}" onsubmit="return confirm('Delete this issue record?')" class="px-4 pb-4">@csrf @method('DELETE')<button class="text-sm font-bold text-rose-600">Delete issue</button></form></details>@endforeach</div>
    @elseif($module === 'calendar' && $role === 'admin')
        <div class="manage-list">@foreach($events as $item)<details class="manage-details"><summary>{{ $item->title }} · {{ $item->starts_at->format('d M') }}</summary><form method="POST" action="{{ route('school-events.update',$item) }}" class="manage-form">@csrf @method('PATCH') @include('modules.forms.event', ['item' => $item])<button class="btn-primary">Save event</button></form><form method="POST" action="{{ route('school-events.destroy',$item) }}" onsubmit="return confirm('Delete this event?')" class="px-4 pb-4">@csrf @method('DELETE')<button class="text-sm font-bold text-rose-600">Delete event</button></form></details>@endforeach</div>
    @elseif($module === 'notices')
        <p class="mt-5 text-sm text-slate-500">Use <strong>Create</strong> above to publish a notice. You can edit your own notices below.</p><div class="manage-list">@foreach($notices as $item)@if($role==='admin'||$item->author_id===auth()->id())<details class="manage-details"><summary>{{ $item->title }}</summary><form method="POST" action="{{ route('notices.update',$item) }}" class="manage-form">@csrf @method('PATCH')<div><label>Title</label><input name="title" value="{{ $item->title }}" required></div><div><label>Audience</label><select name="audience">@foreach(['all','teacher','student','parent'] as $audience)<option @selected($item->audience===$audience)>{{ $audience }}</option>@endforeach</select></div><div><label>Priority</label><select name="priority">@foreach(['normal','important','urgent'] as $priority)<option @selected($item->priority===$priority)>{{ $priority }}</option>@endforeach</select></div><div class="sm:col-span-2"><label>Notice</label><textarea name="body" rows="4" required>{{ $item->body }}</textarea></div><button class="btn-primary">Save notice</button></form><form method="POST" action="{{ route('notices.destroy',$item) }}" onsubmit="return confirm('Delete this notice?')" class="px-4 pb-4">@csrf @method('DELETE')<button class="text-sm font-bold text-rose-600">Delete notice</button></form></details>@endif @endforeach</div>
    @elseif($module === 'leave')
        <div class="manage-list">@foreach($leaves->where('user_id',auth()->id())->where('status','pending') as $item)<div class="flex flex-col gap-3 rounded-xl border border-slate-200 p-4 sm:flex-row sm:items-center sm:justify-between"><div><p class="font-bold">{{ $item->from_date->format('d M') }} – {{ $item->to_date->format('d M Y') }}</p><p class="text-sm text-slate-500">{{ $item->reason }}</p></div><form method="POST" action="{{ route('leave.cancel',$item) }}" onsubmit="return confirm('Cancel this leave request?')">@csrf @method('PATCH')<button class="btn-secondary text-rose-600">Cancel request</button></form></div>@endforeach</div>
    @elseif(in_array($module, ['messages','doubts']))
        <div class="manage-list">@forelse($messages->where('sender_id',auth()->id()) as $item)<div class="flex flex-col gap-3 rounded-xl border border-slate-200 p-4 sm:flex-row sm:items-center sm:justify-between"><div><p class="font-bold">{{ $item->subject }}</p><p class="text-sm text-slate-500">Sent to {{ $item->recipient->name }}</p></div><form method="POST" action="{{ route('messages.destroy',$item) }}" onsubmit="return confirm('Remove this sent message?')">@csrf @method('DELETE')<button class="btn-secondary text-rose-600">Delete</button></form></div>@empty<p class="py-5 text-sm text-slate-500">No sent messages yet.</p>@endforelse</div>
    @elseif($module === 'profile')
        <form method="POST" action="{{ route('profile.update') }}" class="manage-form">@csrf @method('PATCH')<div><label>Name</label><input name="name" value="{{ auth()->user()->name }}" required></div><div><label>Email</label><input type="email" name="email" value="{{ auth()->user()->email }}" required></div><div><label>Phone</label><input name="phone" value="{{ auth()->user()->phone }}"></div><div><label>New password</label><input type="password" name="password" minlength="8" autocomplete="new-password"></div><div><label>Confirm new password</label><input type="password" name="password_confirmation" autocomplete="new-password"></div><button class="btn-primary">Update profile</button></form>
    @elseif(in_array($module, ['ptm','support']) && $role === 'parent')
        <p class="mt-5 text-sm text-slate-500">Use the primary action above to create a request. Open requests you created can be edited or deleted below.</p><div class="manage-list">@foreach($records->where('creator_id',auth()->id())->whereIn('status',['open','requested','processing','draft']) as $item)<details class="manage-details"><summary><span>{{ $item->title }}</span><span class="status-{{ $item->status }}">{{ $item->status }}</span></summary><form method="POST" action="{{ route('module-records.update',$item) }}" class="manage-form">@csrf @method('PATCH') @include('modules.forms.module-record', ['item' => $item])<button class="btn-primary">Save request</button></form><form method="POST" action="{{ route('module-records.destroy',$item) }}" onsubmit="return confirm('Delete this request?')" class="px-4 pb-4">@csrf @method('DELETE')<button class="text-sm font-bold text-rose-600">Delete request</button></form></details>@endforeach</div>
    @endif
</section>
@endif
