@php $studentChoices=$role==='admin' ? $users->where('role','student') : ($role==='teacher' ? $attendanceStudents : $children); $formModule=$item?->module ?? ($recordModule ?? $module); @endphp
<input type="hidden" name="module" value="{{ $formModule }}"><input type="hidden" name="audience" value="{{ $item?->audience ?? ($role==='parent'?'parent':'all') }}">
<div><label>Title</label><input name="title" value="{{ old('title',$item?->title) }}" required></div><div><label>Summary / label</label><input name="subtitle" value="{{ old('subtitle',$item?->subtitle) }}"></div>
<div class="sm:col-span-2"><label>Description</label><textarea name="description" rows="3">{{ old('description',$item?->description) }}</textarea></div>
<div><label>Status</label><select name="status">@foreach(['draft','active','scheduled','published','in-progress','complete','issued','ready','processing','configured','positive','resolved','open','closed','requested','confirmed','cancelled','read','unread'] as $status)<option value="{{ $status }}" @selected(old('status',$item?->status ?? ($module==='support'?'open':'active'))===$status)>{{ str($status)->headline() }}</option>@endforeach</select></div>
<div><label>Date / time</label><input type="datetime-local" name="occurred_at" value="{{ old('occurred_at',$item?->occurred_at?->format('Y-m-d\TH:i')) }}"></div>
@if(in_array($formModule,['feedback','behavior','ptm','documents','certificates','support']))<div><label>Learner</label><select name="student_id"><option value="">General record</option>@foreach($studentChoices as $child)<option value="{{ $child->id }}" @selected(old('student_id',$item?->student_id)===$child->id)>{{ $child->name }}</option>@endforeach</select></div>@endif
@if(in_array($formModule,['curriculum','timetable','exams','feedback','chapters']))<div><label>Subject</label><select name="subject_id"><option value="">General</option>@foreach($subjects as $subject)<option value="{{ $subject->id }}" @selected(old('subject_id',$item?->subject_id)===$subject->id)>{{ $subject->name }}</option>@endforeach</select></div>@endif
@if($role==='admin')<div><label>Owner</label><select name="owner_id"><option value="{{ auth()->id() }}">{{ auth()->user()->name }}</option>@foreach($users->where('role','teacher') as $teacher)<option value="{{ $teacher->id }}" @selected(old('owner_id',$item?->owner_id)===$teacher->id)>{{ $teacher->name }}</option>@endforeach</select></div><div><label>Audience</label><select name="audience">@foreach(['all','admin','teacher','student','parent'] as $audience)<option value="{{ $audience }}" @selected(old('audience',$item?->audience ?? 'all')===$audience)>{{ str($audience)->headline() }}</option>@endforeach</select></div>@endif
@if($formModule==='timetable')<div><label>Day</label><select name="day">@foreach(['Mon','Tue','Wed','Thu','Fri','Sat'] as $day)<option @selected(old('day',$item?->meta['day']??null)===$day)>{{ $day }}</option>@endforeach</select></div><div><label>Period</label><input type="number" name="period" min="1" max="10" value="{{ old('period',$item?->meta['period']??1) }}"></div><div><label>Room</label><input name="room" value="{{ old('room',$item?->meta['room']??null) }}"></div>@endif
@if(in_array($formModule,['curriculum','chapters']))<div><label>Progress %</label><input type="number" name="progress" min="0" max="100" value="{{ old('progress',$item?->meta['progress']??0) }}"></div>@endif
@if(in_array($formModule,['documents','certificates']))<div class="sm:col-span-2"><label>Attachment <span class="font-normal text-slate-400">PDF, JPG or PNG · max 5 MB</span></label><input type="file" name="attachment" accept=".pdf,.jpg,.jpeg,.png">@if(data_get($item?->meta,'attachment_path'))<a class="mt-2 inline-flex text-sm font-bold text-brand-700" href="{{ route('module-records.download',$item) }}">Download {{ data_get($item->meta,'original_name','attachment') }}</a>@endif</div>@endif
